name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  dispatch:
    if: github.repository == 'mikf/gallery-dl'
    runs-on: ubuntu-24.04

    steps:
      - name: Dispatch to gdl-org/docs
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gdl-org/docs/actions/workflows/pages.yml/dispatches \
          -d '{"ref":"master"}'

  deploy:
    if: github.repository == 'mikf/gallery-dl'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure pages
        uses: actions/configure-pages@v5

      - name: Copy static files
        run: |
          mkdir --parents -- ./_site
          cp --archive --target-directory=./_site -- \
            ./docs/oauth-redirect.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
      
      - name: Deploy pages
        uses: actions/deploy-pages@v4
        id: deployment
